version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017" # Map MongoDB's default port to your local machine
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always
    volumes:
      - mongodb_data:/data/db # Persist data across container restarts
    

volumes:
  mongodb_data:
